/** Application */
export const ERROR_TIMED_OUT = 'ERROR_TIMED_OUT';
export const APP_FETCH_REQUESTED = 'APP_FETCH_REQUESTED';
export const APP_FETCH_FAILED = 'APP_FETCH_FAILED';
export const APP_REQUEST_FAILED = 'APP_REQUEST_FAILED';
/** Authorization */
export const AUTH_LOGGED_IN = 'AUTH_LOGGED_IN';
export const AUTH_LOGGED_OUT = 'AUTH_LOGGED_OUT';
/** Cards */
export const CARDS_POPULAR_SKIPPED = 'CARDS_POPULAR_SKIPPED';
export const CARDS_POPULAR_LIKED = 'CARDS_POPULAR_LIKED';
export const CARDS_LIKED_REMOVED = 'CARDS_LIKED_REMOVED';

export const CARDS_FETCH_MORE_SUCCEEDED = 'CARDS_FETCH_MORE_SUCCEEDED';
export const CARDS_FETCH_MORE_REQUESTED = 'CARDS_FETCH_MORE_REQUESTED';

export const CARDS_FETCH_REQUESTED = 'CARDS_FETCH_REQUESTED';
export const CARDS_FETCH_SUCCEEDED = 'CARDS_FETCH_SUCCEEDED';
export const CARDS_FETCH_FAILED = 'CARDS_FETCH_FAILED';