/** Application */
export const APP_ERROR_OCCURED = 'APP_ERROR_OCCURED';
/** Authorization */
export const AUTH_LOGGED_IN = 'AUTH_LOGGED_IN';
export const AUTH_LOGGED_OUT = 'AUTH_LOGGED_OUT';
/** Cards */
export const CARDS_POPULAR_SKIPPED = 'CARDS_POPULAR_SKIPPED';
export const CARDS_POPULAR_LIKED = 'CARDS_POPULAR_LIKED';
export const CARDS_LIKED_REMOVED = 'CARDS_LIKED_REMOVED';
export const CARDS_FETCH_SUCCEEDED = 'CARDS_FETCH_SUCCEEDED';