/** Application */
export const ERROR_TIMED_OUT = 'ERROR_TIMED_OUT';
/** Authorization */
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_SUCCEEDED = 'REGISTER_SUCCEEDED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
/** Cards */
export const CARD_LIKED = 'CARD_LIKED';
export const CARD_DISLIKED = 'CARD_DISLIKED';
export const CARDS_FETCH_REQUESTED = 'CARDS_FETCH_REQUESTED';
export const CARDS_FETCH_SUCCEEDED = 'CARDS_FETCH_SUCCEEDED';
export const CARDS_FETCH_FAILED = 'CARDS_FETCH_FAILED';